services:
  yafm:
    image: yafm:${TAG:-latest}
    container_name: yafm
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - yafm_postgres

  yafm_postgres:
    image: postgres:16.8-alpine3.20
    container_name: yafm_postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
