services:
  yafm:
    image: yafm:${TAG}
    build:
      context: ./
      args:
        VITE_EXRATES_API: ${VITE_EXRATES_API}
        VITE_ACCOUNT_URL: ${VITE_ACCOUNT_URL}
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5173:8080"
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: always
