services:
  yafm:
    image: yafm:${TAG}
    container_name: yafm
    build:
      context: ./
      args:
        VITE_EXRATES_API: ${VITE_EXRATES_API}
        VITE_ACCOUNT_URL: ${VITE_ACCOUNT_URL}
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5173:8080"
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: always

  yafm_postgres:
    image: postgres:16.8-alpine3.20
    container_name: yafm_postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
