/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/commit": {
    /** Commit list */
    get: {
      parameters: {
        query?: {
          /**
           * Format: date-time
           * @example 2017-07-21T17:32:28Z
           */
          syncedAtFrom?: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["Commit"][];
          };
        };
        500: {
          content: {
            "application/json": components["schemas"]["HttpException"];
          };
        };
      };
    };
    /** Create commit */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateCommit"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Commit"];
          };
        };
        500: {
          content: {
            "application/json": components["schemas"]["HttpException"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Commit: {
      /** Format: uuid */
      id: string;
      cipher: string;
      iv: string;
      hmac: string;
      salt: string;
      /** Format: uuid */
      userId: string;
      /** Format: date-time */
      syncedAt: string;
    };
    CreateCommit: {
      cipher: string;
      iv: string;
      hmac: string;
      salt: string;
    };
    HttpException: {
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
